[package]
name = "lesson04"
version = "0.1.0"
authors = ["tomohiko <tom-i@din.or.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
